### ISSUE TITLE
How can I run inference on images after procuring the llava_v1 weights?

### ISSUE THREAD

**Issue by kenhuang1964** [SALT-NLP/LLaVAR#5]
Hey guys, once I have the merged weights, how can I run inference on a single image? Do I need to fine-tune the model further before doing that? Also, is an A10 instance capable of running inference on a single image with this model?

**Comment by StevenyzZhang** [comment]
```
python -m llava.eval.run_llava \
    --model-name /path/to/checkpoint \
    --image-file "https://cdn.shopify.com/s/files/1/0057/3728/3618/products/a-man-called-otto_ezrjr0pm_480x.progressive.jpg" \
    --query "Who starred in the movie?"
```

Here is an example of running QA on a given image.
Make sure "v1" is included in your folder name so that the correct conversation mode is used.

In my previous experience, A10G 20GB is not enough. A100 40GB is okay with the current code. You might want to add more tricks to make it runnable on A10G.

**Comment by StevenyzZhang** [comment]
BTW, [LLaVA](https://github.com/haotian-liu/LLaVA/blob/main/docs/Release_Notes.md#7192023) now supports 4-bit/8-bit inference, which means less VRAM is needed.
You can try to run our model on their code base if you want.

**Comment by kenhuang1964** [comment]
Thank you @StevenyzZhang :+1:
